---
spring:
  config.activate.on-profile: default
cds:
  datasource:
    auto-config.enabled: false
  odata-v4:
    endpoint:
      path: "/api"
  security.mock.users:
    - name: user
      password: user
      roles:
        - Customer
    - name: admin
      password: admin
      roles:
        - Administrator
